apiVersion: v1

kind: Service

metadata:
  name: front-service
  namespace: ecom-app

spec:
  selector:
    type: front
  type: NodePort
  ports:
  -    port: 5005
       targetPort: 5005
       nodePort: 31900
