apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: ecom-app
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ~/ecom-app-data/db
